- name: Deploy blackbox-exporter & prometheus on man
  hosts:
   - man
  become: true
  roles:
    - role: prometheus
      when: (groups["monitor-os"] is defined) or (groups["monitor-icmp"] is defined) or
        (groups['monitored_hosts'] is defined and (groups['monitored_hosts']|length>0))
    - role: blackbox-exporter
      when: (groups["monitor-os"] is defined) or (groups["monitor-icmp"] is defined) or
        (groups['monitored_hosts'] is defined and (groups['monitored_hosts']|length>0))

- name: Deploy node-exporter on listed Linux hosts
  hosts: monitor-os,!windows_hosts
  become: true
  roles:
    - role: node-exporter
      when:
        - ansible_os_family == 'Debian' or ansible_os_family == 'RedHat' or ansible_os_family == 'FreeBSD'
        - groups["monitor-os"] is defined and (groups["monitor-os"]|length>0)

- name: Deploy node-exporter on all Linux hosts
  hosts: routers,hosts,!proxy-jump,!windows_hosts
  become: true
  roles:
    - role: node-exporter
      when:
        - ansible_os_family == 'Debian' or ansible_os_family == 'RedHat' or ansible_os_family == 'FreeBSD'
        - groups["monitor-os"] is defined and (groups["monitor-os"]|length == 0)

- name: Deploy windows-exporter on listed Windows hosts
  hosts: monitor-os:&windows_hosts
  roles:
    - role: windows-exporter
      when:
        - groups["monitor-os"] is defined and (groups["monitor-os"]|length>0)

- name: Deploy windows-exporter on all Windows hosts
  hosts: windows_hosts
  roles:
    - role: windows-exporter
      when:
        - groups["monitor-os"] is defined and (groups["monitor-os"]|length == 0)
